FROM mcr.microsoft.com/vscode/devcontainers/java:0-11

# [Optional] Install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get -y install --no-install-recommends <your-package-list-here>
